import male from '../assets/images/male-avatar.jpg';

export const usersData = [
  {
    name: 'Jan',
    ActiveUsers: 4000,
  },
  {
    name: 'Feb',
    ActiveUsers: 3000,
  },
  {
    name: 'Mar',
    ActiveUsers: 2000,
  },
  {
    name: 'April',
    ActiveUsers: 2780,
  },
  {
    name: 'May',
    ActiveUsers: 1890,
  },
  {
    name: 'Jun',
    ActiveUsers: 2390,
  },
  {
    name: 'July',
    ActiveUsers: 3490,
  },
  {
    name: 'Aug',
    ActiveUsers: 5490,
  },
  {
    name: 'Sept',
    ActiveUsers: 2490,
  },
  {
    name: 'Oct',
    ActiveUsers: 1490,
  },
  {
    name: 'Nov',
    ActiveUsers: 3490,
  },
  {
    name: 'Dec',
    ActiveUsers: 6490,
  },
];
export const userRows = [
  {
    id: 1,
    userName: 'Jon Snow',
    avatar: male,
    email: 'jon@gmail.com',
    status: 'active',
    transactions: '$ 150.00',
  },
  {
    id: 2,
    userName: 'Jon Snow',
    avatar: male,
    email: 'jon@gmail.com',
    status: 'active',
    transactions: '$ 150.00',
  },
  {
    id: 3,
    userName: 'Jon Snow',
    avatar: male,
    email: 'jon@gmail.com',
    status: 'active',
    transactions: '$ 150.00',
  },
  {
    id: 4,
    userName: 'Jon Snow',
    avatar: male,
    email: 'jon@gmail.com',
    status: 'active',
    transactions: '$ 150.00',
  },
  {
    id: 5,
    userName: 'Jon Snow',
    avatar: male,
    email: 'jon@gmail.com',
    status: 'active',
    transactions: '$ 150.00',
  },
  {
    id: 6,
    userName: 'Jon Snow',
    avatar: male,
    email: 'jon@gmail.com',
    status: 'active',
    transactions: '$ 150.00',
  },
  {
    id: 7,
    userName: 'Jon Snow',
    avatar: male,
    email: 'jon@gmail.com',
    status: 'active',
    transactions: '$ 150.00',
  },
  {
    id: 8,
    userName: 'Jon Snow',
    avatar: male,
    email: 'jon@gmail.com',
    status: 'active',
    transactions: '$ 150.00',
  },
  {
    id: 9,
    userName: 'Jon Snow',
    avatar: male,
    email: 'jon@gmail.com',
    status: 'active',
    transactions: '$ 150.00',
  },
  {
    id: 10,
    userName: 'Jon Snow',
    avatar: male,
    email: 'jon@gmail.com',
    status: 'active',
    transactions: '$ 150.00',
  },
];

export const productData = [
  {
    id: 1,
    name: 'Apple Airpods',
    img: 'https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    stock: 123,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 2,
    name: 'Apple Airpods',
    img: 'https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    stock: 123,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 3,
    name: 'Apple Airpods',
    img: 'https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    stock: 123,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 4,
    name: 'Apple Airpods',
    img: 'https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    stock: 123,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 5,
    name: 'Apple Airpods',
    img: 'https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    stock: 123,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 6,
    name: 'Apple Airpods',
    img: 'https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    stock: 123,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 7,
    name: 'Apple Airpods',
    img: 'https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    stock: 123,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 8,
    name: 'Apple Airpods',
    img: 'https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    stock: 123,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 9,
    name: 'Apple Airpods',
    img: 'https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    stock: 123,
    status: 'active',
    price: '$120.00',
  },
  {
    id: 10,
    name: 'Apple Airpods',
    img: 'https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
    stock: 123,
    status: 'active',
    price: '$120.00',
  },
];
